version: "3.9"

services:
  # 🟢 MongoDB
  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v24.2.2
    container_name: redpanda
    restart: unless-stopped
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --node-id 0
      - --check=false
      - --kafka-addr PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:19092
      - --advertise-kafka-addr PLAINTEXT://redpanda:9092,OUTSIDE://localhost:19092
      - --pandaproxy-addr 0.0.0.0:8082
      - --advertise-pandaproxy-addr localhost:8082
      - --schema-registry-addr 0.0.0.0:8081
    ports:
      - "9092:9092"
      - "19092:19092"
      - "8081:8081"     # Schema Registry
      - "8082:8082"     # Pandaproxy
      - "9644:9644"     # Admin API
    volumes:
      - redpanda_data:/var/lib/redpanda/data

  # 📊 Redpanda Console (UI)
  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:v2.8.1
    container_name: redpanda-console
    restart: unless-stopped
    ports:
      - "8088:8080"
    environment:
      KAFKA_BROKERS: redpanda:9092
      SCHEMA_REGISTRY_ENABLED: "true"
      SCHEMA_REGISTRY_URLS: http://redpanda:8081
    depends_on:
      - redpanda

volumes:
  mongo_data:
    driver: local
  redpanda_data:
    driver: local